@extends('layouts.app')

@section('content')
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Landing Page</title>
</head>
<body style="background-color: EFECE5;">

<!--
    Div 1 : Hero Section,  Background image, perkenalan, 2 button
-->
<div class="flex py-20 px-8 relative justify-center">
    <div class="container flex flex-col-reverse lg:flex-row items-center gap-12 mt-14 lg:mt-12">
        <div class="flex flex-1 flex-col items-center lg:items-start">
            <h2 class="text-leaf font-bold md:text-5xl lg:text-5xl mt-4 mb-6">
                Selamat Datang
                <h3 class="text-leaf font-bold md:text-5xl lg:text-5xl mt-4 mb-6">
                di Kupitilizer
                </h3>
            </h2>
            <p class="text-gray text-45 font-bold md:text-4xl mt-6">
                Mari tukarkan limbah ampas kopi </p> 
            <p class="text-gray text-45 font-bold md:text-4xl mt-6 mb-10">   
                anda menjadi <span class="text-leaf md:text-4xl">pupuk</span>
            </p>
            <div class="flex justify-center flex-wrap gap-8">
                <button type="button" class="bg-leaf hover:bg-leaf text-gray font-bold py-2 px-4 rounded">JOIN NOW</button>
                <button type="button" class="bg-dark hover:bg-dark text-gray font-bold py-2 px-4 rounded">CONTACT US</button>
            </div>
        </div>
    </div>
  </div>
<!--
    Div 2 : Background image, deskripsi What is Kupilizer? sama icon
-->
<div class="flex py-20 px-8 relative justify-center">
    <div class="max-w-6xl mx-auto">
      <h2 class="text-4xl md:text-5xl font-bold text-left text-dark mb-10">
        What is <span class="text-dark">Kupitilizer?</span>
      </h2>
      <div class="flex flex-col lg:flex-row items-center lg:justify-between">
        <div class="lg:w-1/2 lg:pr-8 mb-8 lg:mb-0">
          <p class="text-dark text-xl leading-relaxed">
            Kupitilizer is a minimalistic app that has environmental benefits. It features the ability to exchange wasted coffee grounds into organic compost for various plants. Coffee grounds can be a factor in contamination. Kupitilizer also provides other coffee grounds products such as soap, bricks, and other cosmetic products.
          </p>
          <p class="mt-6 text-dark text-xl leading-relaxed">
            With this Kupitilizer, it can help reduce environmental pollution waste and reduce coffee waste generated by almost all communities.
          </p>
          <p class="text-dark mt-10 text-lg">
            "Call Request - Keep Go Green"
          </p>
        </div>
      </div>
    </div>
</div>
<!--
    Div 3: Background image, Our Features 
-->
<div class="text-center text-gray py-16 id="Features">
    <div class="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
      <h2 class="text-3xl text-center font-bold text-gray mb-8">Our <span class="text-leaf text-center font-bold text-3xl mb-8">Features</span></h2>
      <div class="flex justify-between items-center gap-12">
        <div class="flex flex-col items-center">
          <div class="rounded-full bg-leaf h-24 w-24 flex items-center justify-center mb-4">
            <svg class="w-8 h-8 text-gray" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg">
              <image xlink:href="{{ asset('images/icon1.png') }}" height="24" width="24"/>
            </svg>
          </div>
          <h3 class="text-xl font-bold text-gray mb-2">Membuat Request</h3>
        </div>
        <div class="flex flex-col items-center">
          <div class="rounded-full bg-leaf h-24 w-24 flex items-center justify-center mb-4">
            <svg class="w-8 h-8 text-gray" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg">
              <image xlink:href="{{ asset('images/icon2.png') }}" height="24" width="24"/>
            </svg>
          </div>
          <h3 class="text-xl font-bold text-gray mb-2">Info Produk</h3>
        </div>
        <div class="flex flex-col items-center">
          <div class="rounded-full bg-leaf h-24 w-24 flex items-center justify-center mb-4">
            <svg class="w-8 h-8 text-gray" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg">
              <image xlink:href="{{ asset('images/icon3.png') }}" height="24" width="24"/>
            </svg>
          </div>
          <h3 class="text-xl font-bold text-gray mb-2">Redeem Kupon</h3>
        </div>
      </div>
    </div>
  </div>
</body>
</html>
@endsection